# Generated by Django 4.1.5 on 2023-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('stopId', models.IntegerField(primary_key=True, serialize=False)),
                ('stopName', models.CharField(max_length=200)),
                ('subName', models.CharField(max_length=200)),
                ('stopLat', models.FloatField()),
                ('stopLon', models.FloatField()),
                ('nonpassenger', models.BooleanField()),
            ],
        ),
    ]
