# Generated by Django 4.1.5 on 2023-01-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='MainForm',
        ),
    ]
