# Generated by Django 4.1.5 on 2023-01-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_rename_index_mainform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainForm',
            new_name='Stop',
        ),
    ]
